[package]
name = "prost-google-rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.14"
prost-types = "0.14"
tonic = "0.14"

[build-dependencies]
tonic-prost-build = "0.14"

[lints.clippy]
all = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

missing_const_for_fn = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
